version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
  # Define the jobs we want to run for this project
jobs:
   # Exercise: Config and Deployment
  create_and_deploy_front_end:
    docker:
        - image: amazon/aws-cli
    steps:
        - checkout
        - run:
            name: Execute bucket.yml - Create Cloudformation Stack
            command: |
                aws cloudformation deploy \
                --template-file bucket.yml \
                --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
                --parameter-overrides MyBucketName="kapil-bucket-${CIRCLE_WORKFLOW_ID:0:7}"
                
        - run: aws s3 sync ./*.html s3://kapil-bucket-${CIRCLE_WORKFLOW_ID:0:7} --delete
   
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_and_deploy_front_end
